
terraform {
  required_providers {
    stepsecurity = {
      source = "step-security/stepsecurity"
    }
  }
}

provider "stepsecurity" {
  api_key  = "xxxxxxxx" # can also be set as env variable STEP_SECURITY_API_KEY
  customer = "abcdefg"  # can also be set as env variable STEP_SECURITY_CUSTOMER
}

# Configure PR template for policy-driven PRs
resource "stepsecurity_github_pr_template" "example" {
  owner          = "test-organization"
  title          = "[StepSecurity] Apply security best practices"
  summary        = <<-EOT
    ## Summary

    This pull request has been generated by [StepSecurity](https://int1.stepsecurity.io/github/shubham-stepsecurity/actions/dashboard) as part of your enterprise subscription to ensure compliance with recommended security best practices. Please review and merge the pull request to apply these security enhancements.

    ## Security Fixes

    {{STEPSECURITY_SECURITY_FIXES}}

    ## Feedback
    For bug reports, feature requests, and general feedback; please create an issue in [step-security/secure-repo](https://github.com/step-security/secure-repo) or contact us via [our website](https://www.stepsecurity.io/).
  EOT
  commit_message = <<-EOT
    [StepSecurity] Apply security best practices

    Signed-off-by: StepSecurity Bot <bot@stepsecurity.io>
  EOT
  labels         = ["security", "automated"]

  # Optional. Template for the remediation PR branch name. Must contain {time},
  # which is replaced with a DDHHMM timestamp so each PR gets a unique branch.
  # Omit to use the default branch name.
  branch_name = "chore-GHA-{time}-stepsecurity-remediation"
}

# For importing existing PR template config to terraform state
# this will be helpful to manage existing PR template config using terraform
# alternative to this is to use terraform import command
import {
  to = stepsecurity_github_pr_template.example
  id = "test-organization"
}
