package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	stepsecurityapi "github.com/step-security/terraform-provider-stepsecurity/internal/stepsecurity-api"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                = &developerMDMPackageConfigPolicyResource{}
	_ resource.ResourceWithConfigure   = &developerMDMPackageConfigPolicyResource{}
	_ resource.ResourceWithImportState = &developerMDMPackageConfigPolicyResource{}
)

// NewDeveloperMDMPackageConfigPolicyResource is a helper function to simplify the provider implementation.
func NewDeveloperMDMPackageConfigPolicyResource() resource.Resource {
	return &developerMDMPackageConfigPolicyResource{}
}

// developerMDMPackageConfigPolicyResource is the resource implementation.
type developerMDMPackageConfigPolicyResource struct {
	client stepsecurityapi.Client
}

// developerMDMPackageConfigPolicyModel maps the resource schema data. Unlike the IDE
// extension policy, package_config carries no rules and no user-facing mode: the backend
// enforces a single meaningful mode (allowlist, "the allowed registry"), so it is not
// exposed here.
type developerMDMPackageConfigPolicyModel struct {
	ID           types.String `tfsdk:"id"`
	PolicyID     types.String `tfsdk:"policy_id"`
	Name         types.String `tfsdk:"name"`
	Description  types.String `tfsdk:"description"`
	Target       types.String `tfsdk:"target"`
	RegistryType types.String `tfsdk:"registry_type"`
	CreatedBy    types.String `tfsdk:"created_by"`
	CreatedAt    types.String `tfsdk:"created_at"`
	UpdatedBy    types.String `tfsdk:"updated_by"`
	UpdatedAt    types.String `tfsdk:"updated_at"`
}

// Metadata returns the resource type name.
func (r *developerMDMPackageConfigPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_developer_mdm_package_config_policy"
}

// Schema defines the schema for the resource.
func (r *developerMDMPackageConfigPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Developer MDM package manager configuration policy in StepSecurity. " +
			"The policy points a managed device's npm configuration (the user-level `.npmrc`) at the tenant's " +
			"StepSecurity secure registry; StepSecurity compiles and enforces it on assigned devices. The registry " +
			"URL and the tenant's registry auth key are injected by StepSecurity at compile time and are never part of this " +
			"resource. Creating or updating a policy fails with a 409 while the tenant's StepSecurity secure " +
			"registry is not onboarded.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier. Same value as `policy_id`.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"policy_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The unique identifier for this policy generated by StepSecurity.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The name of the policy.",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Optional human-readable description.",
			},
			"target": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(stepsecurityapi.DeveloperMDMTargetNPM),
				MarkdownDescription: "Package ecosystem this policy governs. Defaults to `npm` (the only supported target).",
				Validators: []validator.String{
					stringvalidator.OneOf(stepsecurityapi.DeveloperMDMTargetNPM),
				},
			},
			"registry_type": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Default:  stringdefault.StaticString(stepsecurityapi.DeveloperMDMRegistryTypeStepSecurity),
				MarkdownDescription: "Which registry the managed npm config points at. Defaults to `stepsecurity` " +
					"(the tenant's StepSecurity secure registry), the only supported value in v1.",
				Validators: []validator.String{
					stringvalidator.OneOf(stepsecurityapi.DeveloperMDMRegistryTypeStepSecurity),
				},
			},
			"created_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The user who created this policy.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The timestamp when this policy was created.",
			},
			"updated_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The user who last updated this policy.",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The timestamp when this policy was last updated.",
			},
		},
	}
}

// Configure adds the provider configured client to the resource.
func (r *developerMDMPackageConfigPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(stepsecurityapi.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected stepsecurityapi.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

// Create creates the resource and sets the initial Terraform state.
func (r *developerMDMPackageConfigPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan developerMDMPackageConfigPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiReq := buildDeveloperMDMPackageConfigPolicyRequest(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	created, err := r.client.CreateDeveloperMDMPolicy(ctx, apiReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating Developer MDM package config policy",
			"Could not create policy, unexpected error: "+err.Error()+
				"\n\nA 409 here means the tenant's StepSecurity secure registry is not onboarded. "+
				"Onboard it in the StepSecurity console before creating this policy.",
		)
		return
	}

	applyDeveloperMDMPackageConfigPolicyToModel(created, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read refreshes the Terraform state with the latest data.
func (r *developerMDMPackageConfigPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state developerMDMPackageConfigPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	policy, err := r.client.GetDeveloperMDMPolicy(ctx, state.PolicyID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading Developer MDM package config policy",
			"Could not read policy ID "+state.PolicyID.ValueString()+": "+err.Error(),
		)
		return
	}

	applyDeveloperMDMPackageConfigPolicyToModel(policy, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *developerMDMPackageConfigPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan developerMDMPackageConfigPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiReq := buildDeveloperMDMPackageConfigPolicyRequest(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	updated, err := r.client.UpdateDeveloperMDMPolicy(ctx, plan.PolicyID.ValueString(), apiReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating Developer MDM package config policy",
			"Could not update policy, unexpected error: "+err.Error(),
		)
		return
	}

	applyDeveloperMDMPackageConfigPolicyToModel(updated, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the resource and removes the Terraform state on success.
func (r *developerMDMPackageConfigPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state developerMDMPackageConfigPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteDeveloperMDMPolicy(ctx, state.PolicyID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error deleting Developer MDM package config policy",
			"Could not delete policy, unexpected error: "+err.Error(),
		)
		return
	}
}

// ImportState imports the resource by backend policy_id and lets Read populate the rest.
func (r *developerMDMPackageConfigPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("policy_id"), req, resp)
}

// buildDeveloperMDMPackageConfigPolicyRequest converts the model into an API request body.
// It hardcodes the category, spec version, and mode: package_config supports only spec
// version 1 and only mode allowlist, so the request always carries those values.
func buildDeveloperMDMPackageConfigPolicyRequest(model developerMDMPackageConfigPolicyModel, diags *diag.Diagnostics) stepsecurityapi.DeveloperMDMPolicyRequest {
	spec := stepsecurityapi.DeveloperMDMPackageConfigSpec{
		Registry: stepsecurityapi.DeveloperMDMRegistryRef{
			Type: developerMDMPackageConfigRegistryType(model.RegistryType),
		},
	}
	specJSON, err := json.Marshal(spec)
	if err != nil {
		diags.AddError("Failed to encode policy spec", err.Error())
	}

	return stepsecurityapi.DeveloperMDMPolicyRequest{
		Name:        model.Name.ValueString(),
		Description: model.Description.ValueString(),
		Category:    stepsecurityapi.DeveloperMDMCategoryPackageConfig,
		Target:      developerMDMPackageConfigTarget(model.Target),
		SpecVersion: stepsecurityapi.DeveloperMDMSpecVersionPackageConfig,
		Mode:        stepsecurityapi.DeveloperMDMModeAllowlist,
		Spec:        specJSON,
	}
}

// developerMDMPackageConfigTarget defaults an omitted target to npm.
func developerMDMPackageConfigTarget(target types.String) string {
	if target.IsNull() || target.IsUnknown() || target.ValueString() == "" {
		return stepsecurityapi.DeveloperMDMTargetNPM
	}
	return target.ValueString()
}

// developerMDMPackageConfigRegistryType defaults an omitted registry type to stepsecurity.
func developerMDMPackageConfigRegistryType(registryType types.String) string {
	if registryType.IsNull() || registryType.IsUnknown() || registryType.ValueString() == "" {
		return stepsecurityapi.DeveloperMDMRegistryTypeStepSecurity
	}
	return registryType.ValueString()
}

// applyDeveloperMDMPackageConfigPolicyToModel applies an API policy response into the
// Terraform model. It rejects policies whose category is not package_config because this
// resource cannot manage them.
func applyDeveloperMDMPackageConfigPolicyToModel(policy *stepsecurityapi.DeveloperMDMPolicy, model *developerMDMPackageConfigPolicyModel, diags *diag.Diagnostics) {
	if policy.Category != stepsecurityapi.DeveloperMDMCategoryPackageConfig {
		diags.AddError(
			"Unsupported Developer MDM policy category",
			fmt.Sprintf(
				"Policy %q has category %q, but stepsecurity_developer_mdm_package_config_policy only manages %q policies.",
				policy.PolicyID, policy.Category, stepsecurityapi.DeveloperMDMCategoryPackageConfig,
			),
		)
		return
	}

	model.ID = types.StringValue(policy.PolicyID)
	model.PolicyID = types.StringValue(policy.PolicyID)
	model.Name = types.StringValue(policy.Name)
	target := policy.Target
	if target == "" {
		target = stepsecurityapi.DeveloperMDMTargetNPM
	}
	model.Target = types.StringValue(target)
	model.CreatedBy = types.StringValue(policy.CreatedBy)
	model.CreatedAt = types.StringValue(policy.CreatedAt)
	model.UpdatedBy = types.StringValue(policy.UpdatedBy)
	model.UpdatedAt = types.StringValue(policy.UpdatedAt)

	if policy.Description != "" {
		model.Description = types.StringValue(policy.Description)
	} else {
		model.Description = types.StringNull()
	}

	registryType := stepsecurityapi.DeveloperMDMRegistryTypeStepSecurity
	if len(policy.Spec) > 0 {
		var spec stepsecurityapi.DeveloperMDMPackageConfigSpec
		if err := json.Unmarshal(policy.Spec, &spec); err != nil {
			diags.AddError("Failed to decode policy spec", err.Error())
			return
		}
		if spec.Registry.Type != "" {
			registryType = spec.Registry.Type
		}
	}
	model.RegistryType = types.StringValue(registryType)
}
