package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	stepsecurityapi "github.com/step-security/terraform-provider-stepsecurity/internal/stepsecurity-api"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                   = &developerMDMProfileResource{}
	_ resource.ResourceWithConfigure      = &developerMDMProfileResource{}
	_ resource.ResourceWithValidateConfig = &developerMDMProfileResource{}
	_ resource.ResourceWithImportState    = &developerMDMProfileResource{}
)

// developerMDMAssignmentAttrTypes is the object attribute schema for assignment.
var developerMDMAssignmentAttrTypes = map[string]attr.Type{
	"all_devices": types.BoolType,
	"device_ids":  types.SetType{ElemType: types.StringType},
}

// NewDeveloperMDMProfileResource is a helper function to simplify the provider implementation.
func NewDeveloperMDMProfileResource() resource.Resource {
	return &developerMDMProfileResource{}
}

// developerMDMProfileResource is the resource implementation.
type developerMDMProfileResource struct {
	client stepsecurityapi.Client
}

// developerMDMProfileModel maps the resource schema data.
type developerMDMProfileModel struct {
	ID          types.String `tfsdk:"id"`
	ProfileID   types.String `tfsdk:"profile_id"`
	Name        types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	PolicyIDs   types.Set    `tfsdk:"policy_ids"`
	Enforcement types.String `tfsdk:"enforcement"`
	Assignment  types.Object `tfsdk:"assignment"`
	CreatedBy   types.String `tfsdk:"created_by"`
	CreatedAt   types.String `tfsdk:"created_at"`
	UpdatedBy   types.String `tfsdk:"updated_by"`
	UpdatedAt   types.String `tfsdk:"updated_at"`
}

// developerMDMProfileAssignmentModel maps the assignment nested object.
type developerMDMProfileAssignmentModel struct {
	AllDevices types.Bool `tfsdk:"all_devices"`
	DeviceIDs  types.Set  `tfsdk:"device_ids"`
}

// Metadata returns the resource type name.
func (r *developerMDMProfileResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_developer_mdm_profile"
}

// Schema defines the schema for the resource.
func (r *developerMDMProfileResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Developer MDM profile in StepSecurity. A profile bundles one or more Developer MDM " +
			"policies and optionally assigns them to devices. The backend allows at most one policy per category/target per profile. " +
			"Every policy in the profile shares the one `enforcement` channel: either the StepSecurity agent writes the managed " +
			"configuration for all of them (`dmg`), or it writes none of them and only verifies what your own MDM delivered (`mdm`).",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier. Same value as `profile_id`.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"profile_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The unique identifier for this profile generated by StepSecurity.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The name of the profile.",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Optional human-readable description.",
			},
			"policy_ids": schema.SetAttribute{
				ElementType: types.StringType,
				Required:    true,
				MarkdownDescription: "Set of Developer MDM policy IDs bundled by this profile. Must contain at least one ID. " +
					"The backend allows at most one policy per category/target.",
				Validators: []validator.Set{
					setvalidator.SizeAtLeast(1),
					setvalidator.ValueStringsAre(stringvalidator.LengthAtLeast(1)),
				},
			},
			"enforcement": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "On-device enforcement channel for every policy in this profile. " +
					"`dmg`: the StepSecurity agent writes the managed configuration itself. " +
					"`mdm`: verify only — the agent never writes, and instead reports the configuration " +
					"your own MDM (Jamf, Intune, Iru, …) delivered, so StepSecurity can report drift " +
					"against the policy. Use `mdm` together with the " +
					"`stepsecurity_developer_mdm_profile_export` data source.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						stepsecurityapi.DeveloperMDMEnforcementDMG,
						stepsecurityapi.DeveloperMDMEnforcementMDM,
					),
				},
			},
			"assignment": schema.SingleNestedAttribute{
				Optional: true,
				MarkdownDescription: "Optional device assignment. Omit to leave the profile unassigned. " +
					"`all_devices` and `device_ids` are mutually exclusive.",
				Attributes: map[string]schema.Attribute{
					"all_devices": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Default:             booldefault.StaticBool(false),
						MarkdownDescription: "Assign all current and future devices, unless a device-specific profile overrides a device.",
					},
					"device_ids": schema.SetAttribute{
						ElementType:         types.StringType,
						Optional:            true,
						MarkdownDescription: "Explicit device IDs. Cannot be set when `all_devices = true`.",
						Validators: []validator.Set{
							setvalidator.ValueStringsAre(stringvalidator.LengthAtLeast(1)),
						},
					},
				},
			},
			"created_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The user who created this profile.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The timestamp when this profile was created.",
			},
			"updated_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The user who last updated this profile.",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The timestamp when this profile was last updated.",
			},
		},
	}
}

// Configure adds the provider configured client to the resource.
func (r *developerMDMProfileResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(stepsecurityapi.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected stepsecurityapi.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

// ValidateConfig runs local cross-field validation. It does not call the API because
// referenced policy IDs may be unknown during planning.
func (r *developerMDMProfileResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var model developerMDMProfileModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(validateDeveloperMDMProfile(ctx, model)...)
}

// Create creates the resource and sets the initial Terraform state.
func (r *developerMDMProfileResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan developerMDMProfileModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(validateDeveloperMDMProfile(ctx, plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiReq := buildDeveloperMDMProfileRequest(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(validateDeveloperMDMProfilePolicyCategories(ctx, r.client, apiReq.PolicyIDs)...)
	if resp.Diagnostics.HasError() {
		return
	}

	created, err := r.client.CreateDeveloperMDMProfile(ctx, apiReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating Developer MDM profile",
			"Could not create profile, unexpected error: "+err.Error(),
		)
		return
	}

	applyDeveloperMDMProfileToModel(ctx, created, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read refreshes the Terraform state with the latest data.
func (r *developerMDMProfileResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state developerMDMProfileModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	profile, err := r.client.GetDeveloperMDMProfile(ctx, state.ProfileID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading Developer MDM profile",
			"Could not read profile ID "+state.ProfileID.ValueString()+": "+err.Error(),
		)
		return
	}

	applyDeveloperMDMProfileToModel(ctx, profile, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *developerMDMProfileResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan developerMDMProfileModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(validateDeveloperMDMProfile(ctx, plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiReq := buildDeveloperMDMProfileRequest(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(validateDeveloperMDMProfilePolicyCategories(ctx, r.client, apiReq.PolicyIDs)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updated, err := r.client.UpdateDeveloperMDMProfile(ctx, plan.ProfileID.ValueString(), apiReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating Developer MDM profile",
			"Could not update profile, unexpected error: "+err.Error(),
		)
		return
	}

	applyDeveloperMDMProfileToModel(ctx, updated, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the resource and removes the Terraform state on success.
func (r *developerMDMProfileResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state developerMDMProfileModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteDeveloperMDMProfile(ctx, state.ProfileID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error deleting Developer MDM profile",
			"Could not delete profile, unexpected error: "+err.Error(),
		)
		return
	}
}

// ImportState imports the resource by backend profile_id and lets Read populate the rest.
func (r *developerMDMProfileResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("profile_id"), req, resp)
}

// setFullyKnown reports whether a set and all of its elements are known.
// ElementsAs cannot decode unknown elements into Go strings, so element-level
// validation must wait until apply, when references such as another resource's
// computed id have resolved.
func setFullyKnown(s types.Set) bool {
	if s.IsNull() || s.IsUnknown() {
		return false
	}
	for _, e := range s.Elements() {
		if e.IsUnknown() {
			return false
		}
	}
	return true
}

// validateDeveloperMDMProfile enforces local profile invariants mirrored from the backend.
func validateDeveloperMDMProfile(ctx context.Context, model developerMDMProfileModel) diag.Diagnostics {
	var diags diag.Diagnostics

	if setFullyKnown(model.PolicyIDs) {
		var policyIDs []string
		diags.Append(model.PolicyIDs.ElementsAs(ctx, &policyIDs, false)...)
		if len(policyIDs) == 0 {
			diags.AddAttributeError(
				path.Root("policy_ids"),
				"At least one policy is required",
				"`policy_ids` must contain at least one policy ID.",
			)
		}
		for _, id := range policyIDs {
			if id == "" {
				diags.AddAttributeError(
					path.Root("policy_ids"),
					"Empty policy ID",
					"`policy_ids` must not contain empty strings.",
				)
			}
		}
	}

	if model.Assignment.IsNull() || model.Assignment.IsUnknown() {
		return diags
	}

	var assignment developerMDMProfileAssignmentModel
	diags.Append(model.Assignment.As(ctx, &assignment, basetypes.ObjectAsOptions{})...)
	if diags.HasError() {
		return diags
	}

	var deviceIDs []string
	if setFullyKnown(assignment.DeviceIDs) {
		diags.Append(assignment.DeviceIDs.ElementsAs(ctx, &deviceIDs, false)...)
	}

	if assignment.AllDevices.ValueBool() && len(deviceIDs) > 0 {
		diags.AddAttributeError(
			path.Root("assignment"),
			"Conflicting assignment",
			"`all_devices = true` cannot be combined with `device_ids`. Use one or the other.",
		)
	}

	for _, id := range deviceIDs {
		if id == "" {
			diags.AddAttributeError(
				path.Root("assignment").AtName("device_ids"),
				"Empty device ID",
				"`device_ids` must not contain empty strings.",
			)
		}
	}

	return diags
}

// validateDeveloperMDMProfilePolicyCategories loads referenced policies and rejects
// more than one policy in the same category/target. The backend remains the source of truth.
func validateDeveloperMDMProfilePolicyCategories(ctx context.Context, client stepsecurityapi.Client, policyIDs []string) diag.Diagnostics {
	var diags diag.Diagnostics

	categoryTargetToPolicy := make(map[string]string)
	for _, id := range policyIDs {
		policy, err := client.GetDeveloperMDMPolicy(ctx, id)
		if err != nil {
			diags.AddAttributeError(
				path.Root("policy_ids"),
				"Could not load referenced policy",
				fmt.Sprintf("Failed to load policy %q referenced by this profile: %s", id, err.Error()),
			)
			continue
		}
		key := developerMDMCategoryTargetKey(policy.Category, policy.Target)
		if existing, ok := categoryTargetToPolicy[key]; ok {
			diags.AddAttributeError(
				path.Root("policy_ids"),
				"At most one policy per category/target",
				fmt.Sprintf(
					"Policies %q and %q both have category/target %q. A profile may reference at most one policy per category/target.",
					existing, id, key,
				),
			)
			continue
		}
		categoryTargetToPolicy[key] = id
	}

	return diags
}

func developerMDMCategoryTargetKey(category, target string) string {
	if target == "" {
		switch category {
		case stepsecurityapi.DeveloperMDMCategoryIDEExtension:
			target = stepsecurityapi.DeveloperMDMTargetVSCode
		case stepsecurityapi.DeveloperMDMCategoryPackageConfig:
			target = stepsecurityapi.DeveloperMDMTargetNPM
		}
	}
	return category + "#" + target
}

// buildDeveloperMDMProfileRequest converts the model into an API request body.
func buildDeveloperMDMProfileRequest(ctx context.Context, model developerMDMProfileModel, diags *diag.Diagnostics) stepsecurityapi.DeveloperMDMProfileRequest {
	req := stepsecurityapi.DeveloperMDMProfileRequest{
		Name:        model.Name.ValueString(),
		Description: model.Description.ValueString(),
		PolicyIDs:   sortedStringSet(ctx, model.PolicyIDs, diags),
		Enforcement: model.Enforcement.ValueString(),
	}

	if model.Assignment.IsNull() || model.Assignment.IsUnknown() {
		return req
	}

	var assignment developerMDMProfileAssignmentModel
	diags.Append(model.Assignment.As(ctx, &assignment, basetypes.ObjectAsOptions{})...)
	if diags.HasError() {
		return req
	}

	req.Assignment = stepsecurityapi.DeveloperMDMAssignment{
		AllDevices: assignment.AllDevices.ValueBool(),
		DeviceIDs:  sortedStringSet(ctx, assignment.DeviceIDs, diags),
	}

	return req
}

// applyDeveloperMDMProfileToModel applies an API profile response into the Terraform model.
// All backend policy IDs are preserved so future-category policies are not dropped.
func applyDeveloperMDMProfileToModel(ctx context.Context, profile *stepsecurityapi.DeveloperMDMProfile, model *developerMDMProfileModel, diags *diag.Diagnostics) {
	model.ID = types.StringValue(profile.ProfileID)
	model.ProfileID = types.StringValue(profile.ProfileID)
	model.Name = types.StringValue(profile.Name)
	// Deliberately unguarded: a record with no stored channel must reach state as "" so the
	// next plan shows the diff, rather than leaving a channel the backend does not have.
	model.Enforcement = types.StringValue(profile.Enforcement)
	model.CreatedBy = types.StringValue(profile.CreatedBy)
	model.CreatedAt = types.StringValue(profile.CreatedAt)
	model.UpdatedBy = types.StringValue(profile.UpdatedBy)
	model.UpdatedAt = types.StringValue(profile.UpdatedAt)

	if profile.Description != "" {
		model.Description = types.StringValue(profile.Description)
	} else {
		model.Description = types.StringNull()
	}

	model.PolicyIDs = stringSliceToSet(profile.PolicyIDs, diags)

	// An empty backend assignment (no all_devices, no device IDs) is cosmetically
	// equivalent to an omitted assignment block: both mean "unassigned". Collapse it
	// to null only when the prior config/state also omitted the block or already held
	// an explicit empty object. If the user wrote an explicit (empty) assignment
	// object, preserve that exact shape so a planned object value is not replaced by
	// null, which would fail Terraform's apply-consistency check. If the prior state
	// held a real assignment that the backend has since cleared, fall through to null
	// so the drift is surfaced on read.
	if !profile.Assignment.AllDevices && len(profile.Assignment.DeviceIDs) == 0 {
		if model.Assignment.IsNull() || model.Assignment.IsUnknown() {
			model.Assignment = types.ObjectNull(developerMDMAssignmentAttrTypes)
			return
		}

		var prior developerMDMProfileAssignmentModel
		diags.Append(model.Assignment.As(ctx, &prior, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return
		}
		if !prior.AllDevices.ValueBool() && len(prior.DeviceIDs.Elements()) == 0 {
			// Prior config/state was itself an explicit empty assignment; keep it verbatim.
			return
		}

		model.Assignment = types.ObjectNull(developerMDMAssignmentAttrTypes)
		return
	}

	deviceIDs := types.SetNull(types.StringType)
	if len(profile.Assignment.DeviceIDs) > 0 {
		deviceIDs = stringSliceToSet(profile.Assignment.DeviceIDs, diags)
	}

	assignmentObj, objDiags := types.ObjectValue(developerMDMAssignmentAttrTypes, map[string]attr.Value{
		"all_devices": types.BoolValue(profile.Assignment.AllDevices),
		"device_ids":  deviceIDs,
	})
	diags.Append(objDiags...)
	model.Assignment = assignmentObj
}

// stringSliceToSet converts a string slice into a Terraform set value.
func stringSliceToSet(values []string, diags *diag.Diagnostics) types.Set {
	if len(values) == 0 {
		return types.SetNull(types.StringType)
	}
	elems := make([]attr.Value, len(values))
	for i, v := range values {
		elems[i] = types.StringValue(v)
	}
	setValue, setDiags := types.SetValue(types.StringType, elems)
	diags.Append(setDiags...)
	return setValue
}
